version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=basaltdb
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@POSTGRES:5432/basaltdb?sslmode=disable
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  nextjs:
    build:
      context: .
      dockerfile: nextjs-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://centos-test-api-1:8080
      - NODE_ENV=production
    restart: always
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
