// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type Category struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Client struct {
	ID                  int64  `json:"id"`
	FullName            string `json:"full_name"`
	PhoneWhatsapp       string `json:"phone_whatsapp"`
	PhoneLine           string `json:"phone_line"`
	PetName             string `json:"pet_name"`
	PetBreed            string `json:"pet_breed"`
	AddressStreet       string `json:"address_street"`
	AddressNumber       string `json:"address_number"`
	AddressNeighborhood string `json:"address_neighborhood"`
	AddressReference    string `json:"address_reference"`
}

type Product struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      int64  `json:"user_id"`
}

type ProductCategory struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

type Sale struct {
	ID             int64     `json:"id"`
	ClientID       int64     `json:"client_id"`
	Product        string    `json:"product"`
	Price          int64     `json:"price"`
	Observation    string    `json:"observation"`
	CreatedAt      time.Time `json:"created_at"`
	ChangedAt      time.Time `json:"changed_at"`
	PdfGeneratedAt time.Time `json:"pdf_generated_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}
