// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: sale.sql

package db

import (
	"context"
)

const countSales = `-- name: CountSales :one
SELECT COUNT(*) FROM sale
`

func (q *Queries) CountSales(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSales)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sale (
    client_id,
    product,
    price,
    observation
) VALUES (
    $1, $2, $3, $4
) RETURNING id, client_id, product, price, observation, created_at, changed_at, pdf_generated_at
`

type CreateSaleParams struct {
	ClientID    int64  `json:"client_id"`
	Product     string `json:"product"`
	Price       int64  `json:"price"`
	Observation string `json:"observation"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRowContext(ctx, createSale,
		arg.ClientID,
		arg.Product,
		arg.Price,
		arg.Observation,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Product,
		&i.Price,
		&i.Observation,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.PdfGeneratedAt,
	)
	return i, err
}

const deleteSale = `-- name: DeleteSale :exec
DELETE FROM sale
WHERE id = $1
`

func (q *Queries) DeleteSale(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSale, id)
	return err
}

const getSale = `-- name: GetSale :one
SELECT id, client_id, product, price, observation, created_at, changed_at, pdf_generated_at FROM sale
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSale(ctx context.Context, id int64) (Sale, error) {
	row := q.db.QueryRowContext(ctx, getSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Product,
		&i.Price,
		&i.Observation,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.PdfGeneratedAt,
	)
	return i, err
}

const listSales = `-- name: ListSales :many
SELECT id, client_id, product, price, observation, created_at, changed_at, pdf_generated_at FROM sale
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListSalesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error) {
	rows, err := q.db.QueryContext(ctx, listSales, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sale{}
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Product,
			&i.Price,
			&i.Observation,
			&i.CreatedAt,
			&i.ChangedAt,
			&i.PdfGeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSale = `-- name: UpdateSale :one
UPDATE sale 
SET 
    client_id = COALESCE($2, client_id),
    product = COALESCE($3, product),
    price = COALESCE($4, price),
    observation = COALESCE($5, observation)
WHERE id = $1
RETURNING id, client_id, product, price, observation, created_at, changed_at, pdf_generated_at
`

type UpdateSaleParams struct {
	ID          int64  `json:"id"`
	ClientID    int64  `json:"client_id"`
	Product     string `json:"product"`
	Price       int64  `json:"price"`
	Observation string `json:"observation"`
}

func (q *Queries) UpdateSale(ctx context.Context, arg UpdateSaleParams) (Sale, error) {
	row := q.db.QueryRowContext(ctx, updateSale,
		arg.ID,
		arg.ClientID,
		arg.Product,
		arg.Price,
		arg.Observation,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Product,
		&i.Price,
		&i.Observation,
		&i.CreatedAt,
		&i.ChangedAt,
		&i.PdfGeneratedAt,
	)
	return i, err
}
